import { user, initialUserState,
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOGIN_ATTEMPT,
    SIGNUP_ATTEMPT,
    SIGNUP_SUCCESS,
    SIGNUP_FAILURE,
    SOCIAL_SIGNUP_ATTEMPT,
    SOCIAL_SIGNUP_FAILURE,
    SOCIAL_SIGNUP_SUCCESS,
    LOGOUT_ATTEMPT,
    LOGOUT_SUCCESS,
    PROFILE_ATTEMPT,
    PROFILE_SUCCESS,
    PROFILE_FAILURE,
    LOAD_STATE_ATTEMPT,
    LOAD_SUCCESS,
    CHANGE_ATTEMPT,
    SOCIAL_LOGIN_ATTEMPT,
    CHANGE_IMAGE_ATTEMPT,
    RESET_ERROR,
 } from './userReducer';
//import { serviceReducers, initialServiceState } from './serviceReducer';

const AppReducers = {
    ...user,
    //...serviceReducers
}

const InitialState = {
    ...initialUserState,
    //...initialServiceState
}

const Actions = {
    SOCIAL_LOGIN_ATTEMPT,
    LOGIN_SUCCESS,
    LOGIN_ATTEMPT,
    LOGIN_FAILURE,
    SIGNUP_ATTEMPT,
    SIGNUP_SUCCESS,
    SIGNUP_FAILURE,
    SOCIAL_SIGNUP_ATTEMPT,
    SOCIAL_SIGNUP_FAILURE,
    SOCIAL_SIGNUP_SUCCESS,
    LOGOUT_ATTEMPT,
    LOGOUT_SUCCESS,
    PROFILE_ATTEMPT,
    PROFILE_SUCCESS,
    PROFILE_FAILURE,
    LOAD_STATE_ATTEMPT,
    LOAD_SUCCESS,
    CHANGE_ATTEMPT,
    CHANGE_IMAGE_ATTEMPT,
    RESET_ERROR,
}

export {
    AppReducers,
    InitialState,
    Actions,
    user,
    SOCIAL_LOGIN_ATTEMPT,
    LOGIN_SUCCESS,
    LOGIN_ATTEMPT,
    LOGIN_FAILURE,
    SIGNUP_ATTEMPT,
    SIGNUP_SUCCESS,
    SIGNUP_FAILURE,
    SOCIAL_SIGNUP_ATTEMPT,
    SOCIAL_SIGNUP_FAILURE,
    SOCIAL_SIGNUP_SUCCESS,
    LOGOUT_ATTEMPT,
    LOGOUT_SUCCESS,
    PROFILE_ATTEMPT,
    PROFILE_SUCCESS,
    PROFILE_FAILURE,
    LOAD_STATE_ATTEMPT,
    LOAD_SUCCESS,
    CHANGE_ATTEMPT,
    CHANGE_IMAGE_ATTEMPT,
    RESET_ERROR,
}